### ISSUE TITLE
NPE when javadoc is empty with removehtml converter

### ISSUE THREAD

**Issue by ikeyat** [ikeyat/javadoc2xls#36]
`RemoveHtmlConverter` added at #24 does not take care for `null` input.

**Comment by ikeyat** [comment]
```
[ERROR] java.lang.NullPointerException
[ERROR] at jp.ikeyat.tools.javadoc2xls.report.converter.RemoveHtmlConverter.convert(RemoveHtmlConverter.java:5)
[ERROR] at jp.ikeyat.tools.javadoc2xls.report.writer.CellWriter.write(CellWriter.java:30)
[ERROR] at jp.ikeyat.tools.javadoc2xls.report.TestListBook.writeRow(TestListBook.java:138)
[ERROR] at jp.ikeyat.tools.javadoc2xls.Javadoc2XlsDoclet.execute(Javadoc2XlsDoclet.java:92)
[ERROR] at jp.ikeyat.tools.javadoc2xls.Javadoc2XlsDoclet.start(Javadoc2XlsDoclet.java:32)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
[ERROR] at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
[ERROR] at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:219)
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:205)
[ERROR] at com.sun.tools.javadoc.Main.execute(Main.java:64)
[ERROR] at com.sun.tools.javadoc.Main.main(Main.java:54)
```
